export const initialRes = [
    {
      title: "title 1 still server",
      description: "descriere text",
      category: "restaurant",
      reward: 3,
      price: 50,
      img: "/assets/imgs/pic1.jpg",
      tel: "0742000001",
      email: "a@b.com",
      facebook: "fb",
      web: "www.obiectiv.ro",
      address: "strada x nr y orasul z",
      geolocation: "36.7667,-122.084",
      timetable: "09:00-18:00",
      rating: 45,
    },
    {
      title: "abc 2",
      description: "descriere text",
      category: "cafe",
      reward: 5,
      price: 60,
      img: "/assets/imgs/pic2.jpg",
      tel: "0742000001",
      email: "a@b.com",
      facebook: "fb",
      web: "www.obiectiv.ro",
      address: "strada x nr y orasul z",
      geolocation: "46.7667,24.6",
      timetable: "09:00-18:00",
      rating: 45
    },
    {
      title: "abc 3",
      description: "descriere text",
      category: "muzeu",
      reward: 10,
      price: 55,
      img: "/assets/imgs/pic3.jpg",
      tel: "0742000001",
      email: "a@b.com",
      facebook: "fb",
      web: "www.obiectiv.ro",
      address: "strada x nr y orasul z",
      geolocation: "49.7667,23.6",
      timetable: "09:00-18:00",
      rating: 15
    },
    {
      title: "title 4",
      description: "descriere text",
      category: "restaurant",
      reward: 12,
      price: 45,
      img: "/assets/imgs/pic4.jpg",
      tel: "0742000001",
      email: "a@b.com",
      facebook: "fb",
      web: "www.obiectiv.ro",
      address: "strada x nr y orasul z",
      geolocation: "46.9667,23.6",
      timetable: "09:00-18:00",
      rating: 45
    },
    {
      title: "title 6",
      description: "descriere text",
      category: "hotel",
      reward: 30,
      price: 50,
      img: "/assets/imgs/pic5.jpg",
      tel: "0742000001",
      email: "a@b.com",
      facebook: "fb",
      web: "www.obiectiv.ro",
      address: "strada x nr y orasul z",
      geolocation: "46.8667,23.6",
      timetable: "09:00-18:00",
      rating: 45
    },
    {
      title: "title 7",
      description: "descriere text",
      category: "hotel",
      reward: 22,
      price: 58,
      img: "/assets/imgs/pic6.jpg",
      tel: "0742000001",
      email: "a@b.com",
      facebook: "fb",
      web: "www.obiectiv.ro",
      address: "strada x nr y orasul z",
      geolocation: "46.7667,33.6",
      timetable: "09:00-18:00",
      rating: 45
    }

  ]